name: todo
description: TODO app 

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.2+8

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  cloud_firestore: ^3.1.8
  google_sign_in: ^5.2.4
  get_storage: ^2.0.3
  path_provider: ^2.0.9
  uuid: ^3.0.6
  flutter_slidable: ^1.2.0
  flutter_native_splash: ^2.0.5
  google_mobile_ads: ^1.1.0
  firebase_performance: ^0.8.0+7
  firebase_analytics: ^9.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/to-do-list.png"

flutter_native_splash:
  color: "#aaaaaa"

  image: assets/images/to-do-list.png
  
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/google-icon.png

  