// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5-mXm4vUyYuyqCdOZLpfO2pT9sAEu3pw',
    appId: '1:40096343113:web:3296b0ecb170ff4f9b4b98',
    messagingSenderId: '40096343113',
    projectId: 'get-todoish',
    authDomain: 'get-todoish.firebaseapp.com',
    storageBucket: 'get-todoish.appspot.com',
    measurementId: 'G-VTWPF6GSYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY3K2Z1Vktw8LT79hFZ7AVHgOfg2Cd2Po',
    appId: '1:40096343113:android:5d74b05aebc329b79b4b98',
    messagingSenderId: '40096343113',
    projectId: 'get-todoish',
    storageBucket: 'get-todoish.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD10OVLxSy4L55RsfD3wThdZt5mM5g_brM',
    appId: '1:40096343113:ios:620e2e5d29ee4a4c9b4b98',
    messagingSenderId: '40096343113',
    projectId: 'get-todoish',
    storageBucket: 'get-todoish.appspot.com',
    androidClientId:
        '40096343113-vceq22qgvri6v55478f22ji9g9n20dk6.apps.googleusercontent.com',
    iosClientId:
        '40096343113-4oh7o87v43tqri0tac2nf7bivl8uehhj.apps.googleusercontent.com',
    iosBundleId: 'joao.rafa.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD10OVLxSy4L55RsfD3wThdZt5mM5g_brM',
    appId: '1:40096343113:ios:620e2e5d29ee4a4c9b4b98',
    messagingSenderId: '40096343113',
    projectId: 'get-todoish',
    storageBucket: 'get-todoish.appspot.com',
    androidClientId:
        '40096343113-vceq22qgvri6v55478f22ji9g9n20dk6.apps.googleusercontent.com',
    iosClientId:
        '40096343113-4oh7o87v43tqri0tac2nf7bivl8uehhj.apps.googleusercontent.com',
    iosBundleId: 'joao.rafa.todo',
  );
}
